
import { Lesson } from './types';

export const LESSONS_2025: Lesson[] = [
  { id: 1, title: "Introduction au Livre de Doctrine et Alliances", reference: "Introduction" },
  { id: 2, title: "Témoignage de Joseph Smith", reference: "Joseph Smith—Histoire 1" },
  { id: 3, title: "« Voici, je suis Dieu »", reference: "D&A 1" },
  { id: 4, title: "« Cherche la sagesse »", reference: "D&A 2-5" },
  { id: 5, title: "« Je t’éclairerai l’esprit »", reference: "D&A 6–9" },
  { id: 6, title: "« La première chose que tu dois faire »", reference: "D&A 10-11" },
  { id: 7, title: "« Le fondement de notre Église »", reference: "D&A 12-17" },
  { id: 8, title: "« La valeur des âmes est grande »", reference: "D&A 18-19" },
  { id: 9, title: "« L'organisation et le gouvernement de l'Église »", reference: "D&A 20-22" },
  { id: 10, title: "« Prenez garde à l’orgueil »", reference: "D&A 23-26" },
  { id: 11, title: "« Revêtez toutes les armes de Dieu »", reference: "D&A 27-28" },
  { id: 12, title: "« Rassemblez mes élus »", reference: "D&A 29" },
  { id: 13, title: "« Tu ouvriras la bouche »", reference: "D&A 30-34" },
  { id: 14, title: "« Si vous n’êtes pas un, vous n’êtes pas de moi »", reference: "D&A 35-40" },
  { id: 15, title: "« Cherchez sincèrement les meilleures dons »", reference: "D&A 41-45" },
  { id: 16, title: "« Les lois du royaume de Dieu »", reference: "D&A 46-50" },
  { id: 17, title: "« Un disciple en toutes choses »", reference: "D&A 51-57" },
  { id: 18, title: "« Confessez vos péchés »", reference: "D&A 58-59" },
  { id: 19, title: "« Les habitants de Sion »", reference: "D&A 60-63" },
  { id: 20, title: "« De petites choses procèdent de ce qui est grand »", reference: "D&A 64-66" },
  { id: 21, title: "« Je serai avec vous »", reference: "D&A 67-70" },
  { id: 22, title: "« Que chacun apprenne son devoir »", reference: "D&A 71-75" },
  { id: 23, title: "« La vision des degrés de gloire »", reference: "D&A 76" },
  { id: 24, title: "« Révélations et traduction des Écritures »", reference: "D&A 77-80" },
  { id: 25, title: "« Là où est votre trésor »", reference: "D&A 81-83" },
  { id: 26, title: "« Le serment et l’alliance de la prêtrise »", reference: "D&A 84" },
  { id: 27, title: "« Tenez-vous en des lieux saints »", reference: "D&A 85-87" },
  { id: 28, title: "« Un résumé de la volonté du Seigneur »", reference: "D&A 88" },
  { id: 29, title: "« La Parole de Sagesse »", reference: "D&A 89-92" },
  { id: 30, title: "« La lumière et la vérité »", reference: "D&A 93" },
  { id: 31, title: "« Une maison pour notre Dieu »", reference: "D&A 94-97" },
  { id: 32, title: "« Le camp d’Israël »", reference: "D&A 98-100" },
  { id: 33, title: "« Le rachat de Sion »", reference: "D&A 101-105" },
  { id: 34, title: "« Les Autorités générales et locales »", reference: "D&A 106-108" },
  { id: 35, title: "« Les clés de la prêtrise »", reference: "D&A 109-110" },
  { id: 36, title: "« La parole du Seigneur aux Douze »", reference: "D&A 111-114" },
  { id: 37, title: "« Le nom de l’Église et la loi de la dîme »", reference: "D&A 115-120" },
  { id: 38, title: "« Les épreuves de Joseph Smith »", reference: "D&A 121-123" },
  { id: 39, title: "« L’œuvre pour les morts »", reference: "D&A 124-128" },
  { id: 40, title: "« Instructions de Joseph Smith »", reference: "D&A 129-131" },
  { id: 41, title: "« La nouvelle alliance éternelle du mariage »", reference: "D&A 132" },
  { id: 42, title: "« Le rassemblement d'Israël dispersé »", reference: "D&A 133-134" },
  { id: 43, title: "« Le martyre de Joseph et Hyrum Smith »", reference: "D&A 135-136" },
  { id: 44, title: "« L’œuvre missionnaire et le salut des morts »", reference: "D&A 137–138" },
  { id: 45, title: "Pâques : « Je suis la résurrection et la vie »", reference: "Sujet spécial" },
  { id: 46, title: "Proclamations : La famille et le Christ vivant", reference: "Proclamations" },
  { id: 47, title: "Déclaration officielle 1", reference: "Déclaration officielle 1" },
  { id: 48, title: "Déclaration officielle 2", reference: "Déclaration officielle 2" },
  { id: 49, title: "L'œuvre de l'histoire familiale et du temple", reference: "Thèmes de l'Évangile" },
  { id: 50, title: "La prêtrise et les clés de la prêtrise", reference: "Thèmes de l'Évangile" },
  { id: 51, title: "Devenir des disciples du Sauveur", reference: "Thèmes de l'Évangile" },
  { id: 52, title: "La restauration continue de l'Évangile", reference: "Thèmes de l'Évangile" }
];

export const CURRENT_LESSON_ID = 24;

export const DAYS_OF_WEEK = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"];
